/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MainController;
import controller.SocketClientController;
import java.awt.Adjustable;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import my_swing.Button;


/**
 *
 * @author lazha
 */
public class Main extends javax.swing.JFrame {

    MainController mc;
    /**
     * Creates new form Main
     */
    public Main() {
        mc=new MainController(this);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputSelectType = new javax.swing.JPopupMenu();
        muItImage = new javax.swing.JMenuItem();
        muItFile = new javax.swing.JMenuItem();
        panel_bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spConnected = new javax.swing.JScrollPane();
        dpConnected = new javax.swing.JPanel();
        spChat = new javax.swing.JScrollPane();
        dpChat = new javax.swing.JPanel();
        cmdLogOut = new my_swing.Button();
        inputMsg = new javax.swing.JTextField();
        inputType = new javax.swing.JButton();
        submitMsg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        muItImage.setText("Image");
        muItImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muItImageActionPerformed(evt);
            }
        });
        InputSelectType.add(muItImage);

        muItFile.setText("File");
        muItFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muItFileActionPerformed(evt);
            }
        });
        InputSelectType.add(muItFile);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Discussion");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 102));
        jLabel1.setText("Liste des connectés");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        spConnected.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spConnected.setPreferredSize(new java.awt.Dimension(102, 802));

        dpConnected.setBackground(new java.awt.Color(255, 255, 255));
        dpConnected.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dpConnected.setMinimumSize(new java.awt.Dimension(200, 200));
        dpConnected.setPreferredSize(new java.awt.Dimension(100, 1000));
        spConnected.setViewportView(dpConnected);

        spChat.setAutoscrolls(true);

        dpChat.setBackground(new java.awt.Color(255, 255, 255));
        dpChat.setAutoscrolls(true);
        dpChat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dpChat.setMinimumSize(new java.awt.Dimension(200, 200));
        dpChat.setPreferredSize(new java.awt.Dimension(100, 600));
        spChat.setViewportView(dpChat);

        cmdLogOut.setBackground(new java.awt.Color(255, 255, 255));
        cmdLogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cmdLogOut.setForeground(new java.awt.Color(51, 51, 51));
        cmdLogOut.setText("Sign out");
        cmdLogOut.setColorClick(new java.awt.Color(255, 255, 255));
        cmdLogOut.setColorOver(new java.awt.Color(243, 243, 243));
        cmdLogOut.setFocusable(false);
        cmdLogOut.setFont(new java.awt.Font("Khmer SBBIC Serif", 1, 12)); // NOI18N
        cmdLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLogOutActionPerformed(evt);
            }
        });

        inputMsg.setToolTipText("input");
        inputMsg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        inputType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/more.png"))); // NOI18N
        inputType.setBorder(null);
        inputType.setComponentPopupMenu(InputSelectType);
        inputType.setContentAreaFilled(false);
        inputType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputType.setFocusable(false);
        inputType.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/more_click.png"))); // NOI18N
        inputType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTypeActionPerformed(evt);
            }
        });

        submitMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/send.png"))); // NOI18N
        submitMsg.setBorder(null);
        submitMsg.setContentAreaFilled(false);
        submitMsg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitMsg.setFocusable(false);
        submitMsg.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/send_click.png"))); // NOI18N
        submitMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitMsgActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 102));
        jLabel2.setText("Discussion");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_bgLayout = new javax.swing.GroupLayout(panel_bg);
        panel_bg.setLayout(panel_bgLayout);
        panel_bgLayout.setHorizontalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spConnected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(cmdLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bgLayout.createSequentialGroup()
                        .addComponent(spChat, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(panel_bgLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panel_bgLayout.createSequentialGroup()
                        .addComponent(inputMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputType, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_bgLayout.setVerticalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bgLayout.createSequentialGroup()
                .addGroup(panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spChat, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spConnected, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputType, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void muItImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muItImageActionPerformed
        InputSelectType.setVisible(false);
        mc.setImage();
    }//GEN-LAST:event_muItImageActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        mc.start();
    }//GEN-LAST:event_formWindowOpened

    private void muItFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muItFileActionPerformed
     try {
            InputSelectType.setVisible(false);
            mc.setFile();
        } catch (Exception ex) {
            System.err.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_muItFileActionPerformed

    private void cmdLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLogOutActionPerformed
        int c = JOptionPane.showConfirmDialog(this, "Are you sure you want to sign out ?", "Sign out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (c == JOptionPane.YES_OPTION) {
            try {
                SocketClientController.getClient().close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_cmdLogOutActionPerformed

    private void inputTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTypeActionPerformed
        InputSelectType.show(inputType, inputType.getWidth()/2, inputType.getHeight()/2);
    }//GEN-LAST:event_inputTypeActionPerformed

    private void submitMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitMsgActionPerformed
        System.out.println("submitMsgActionPerformed : 1111");
        System.out.println("inputMsg : "+inputMsg.getText());
        if (!inputMsg.getText().equals("")) {
            try {
                System.out.println("submitMsgActionPerformed : 2222");
                SocketClientController.sendMessage(inputMsg.getText().trim());
                System.out.println("submitMsgActionPerformed : 3333");
                inputMsg.setText("");
                System.out.println("submitMsgActionPerformed : 4444");
                inputMsg.grabFocus();
                System.out.println("submitMsgActionPerformed : 5555");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(Main.this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_submitMsgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public Button getCmdLogOut() {
        return cmdLogOut;
    }

    public void setCmdLogOut(Button cmdLogOut) {
        this.cmdLogOut = cmdLogOut;
    }

    public JPanel getDpChat() {
        return dpChat;
    }

    public void setDpChat(JPanel dpChat) {
        this.dpChat = dpChat;
    }

    public JPanel getDpConnected() {
        return dpConnected;
    }

    public void setDpConnected(JPanel dpConnected) {
        this.dpConnected = dpConnected;
    }

    public JTextField getInputMsg() {
        return inputMsg;
    }

    public void setInputMsg(JTextField inputMsg) {
        this.inputMsg = inputMsg;
    }

    public JButton getInputType() {
        return inputType;
    }

    public void setInputType(JButton inputType) {
        this.inputType = inputType;
    }

    public JMenuItem getMuItFile() {
        return muItFile;
    }

    public void setMuItFile(JMenuItem muItFile) {
        this.muItFile = muItFile;
    }

    public JMenuItem getMuItImage() {
        return muItImage;
    }

    public void setMuItImage(JMenuItem muItImage) {
        this.muItImage = muItImage;
    }

    public JButton getSubmitMsg() {
        return submitMsg;
    }

    public void setSubmitMsg(JButton submitMsg) {
        this.submitMsg = submitMsg;
    }
    
    private void scrollToBottom(JScrollPane scrollPane) {
        JScrollBar verticalBar = scrollPane.getVerticalScrollBar();
        AdjustmentListener downScroller = new AdjustmentListener() {
            @Override
            public void adjustmentValueChanged(AdjustmentEvent e) {
                Adjustable adjustable = e.getAdjustable();
                adjustable.setValue(adjustable.getMaximum());
                verticalBar.removeAdjustmentListener(this);
            }
        };
        verticalBar.addAdjustmentListener(downScroller);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu InputSelectType;
    private my_swing.Button cmdLogOut;
    private javax.swing.JPanel dpChat;
    private javax.swing.JPanel dpConnected;
    private javax.swing.JTextField inputMsg;
    private javax.swing.JButton inputType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem muItFile;
    private javax.swing.JMenuItem muItImage;
    private javax.swing.JPanel panel_bg;
    private javax.swing.JScrollPane spChat;
    private javax.swing.JScrollPane spConnected;
    private javax.swing.JButton submitMsg;
    // End of variables declaration//GEN-END:variables
}
